/* This header file "Routes.h" is created to create a class which define a format for journeys from one airport to another 
This class will be able to read journeys generated by the search function and store them in a vector as individual records.(see DataConfig.cpp)*/

#ifndef _routes_h_	//In order to prevent double definitions.
#define _routes_h_

#include "std_lib_facilities.h"

class Routes
{
public:
	string Journey, Destination, Airline;
	string Origin;
	string Con1;	// Con1 means the first connection airport point between the Origin Airport and Destination Airport
	string Con2;	// Con2 means the second connection airport point
	int Cost;		// Cost means the cost of the flight excluding Departure Tax
	int FlightDur;	// FlightDur means the Duration of the Journey including the sum of Connection Time
	int DTax;		// DTax means Sum of Departure Tax of each journey
	int ConT;		// ConT means Sum of Connection Time of each journey
	int TPrice;		// TPrice means the Total Price of each journey

	Routes(string Jour, string Orig, string c1, string c2, string Dest, string Air,  int Price, int Dur, int Tax, int ConT,int TPrice) 
		/* Constructor: This format is Origin Airport, Connection from Airport 1, Connection from Airport 2, Destination Airport, Airlines, Price (excluding Tax), 
			Duration, Sum of Airport tax, Sum of Connection Time, Total Price.*/
		:Journey(Jour),Origin(Orig),Con1(c1), Con2(c2),Destination(Dest),Airline(Air),Cost(Price),FlightDur(Dur),DTax(Tax),ConT(ConT),TPrice(TPrice){};
			// Orig will be stored as Origin, c1 will be stored as Con1 ...etc.

};

#endif
